package utility;

/**The position of the element in a BlockShape
 * Eg: for 3x3 blockShape, the position of row 2 col 1
 * can be represented by new ElementPos(2,1)*/
public class ElementPos{
	public static final int INITIAL_COL_NUM = 0;
	public static final int INITIAL_ROW_NUM = 0;

	public int row;
	public int col;

	public ElementPos(){
		this(INITIAL_ROW_NUM,INITIAL_COL_NUM);
	}

	public ElementPos(final int row, final int col){
		this.row = row;
		this.col = col;
	}

	public boolean equals(Object otherPos){
		if (otherPos == null) return false;
		if (otherPos == this) return true;
		if (!(otherPos instanceof ElementPos))return false;
		if(getClass() != otherPos.getClass()) return false;

		ElementPos anotherPos = (ElementPos)otherPos;
		//compare the row and col of the ElementPos object
		if(anotherPos.row == this.row && anotherPos.col == this.col){
			return true;
		}else{
			return false;
		}
	}

	/**
	 * generated by eclipse!
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode(){
		final int prime = 31;
		int result = 1;
		result = prime * result + row;
		result = prime * result + col;
		return result;
	}
}


