package rules.BeatIt.Songs;

import rules.BeatIt.Beats;
import rules.BeatIt.Beats.Position;


public class Hatsune_Miku_World_Is_Mine extends Song{
  
  public Hatsune_Miku_World_Is_Mine() { // Maybe add argument if you want to adjust difficulty or speed?
	populateSteps();
	setVariables();
  }

  @Override
  protected void populateSteps() {
	Beats beat = new Beats(193, Position.A);
	steps.add(beat);
	beat = new Beats(214, Position.A);
	steps.add(beat);
	beat = new Beats(276, Position.A);
	steps.add(beat);
	beat = new Beats(287, Position.A);
	steps.add(beat);
	beat = new Beats(326, Position.A);
	steps.add(beat);
	beat = new Beats(343, Position.A);
	steps.add(beat);
	beat = new Beats(362, Position.A);
	steps.add(beat);
	beat = new Beats(373, Position.A);
	steps.add(beat);
	beat = new Beats(383, Position.A);
	steps.add(beat);
	beat = new Beats(404, Position.A);
	steps.add(beat);
	beat = new Beats(425, Position.A);
	steps.add(beat);
	beat = new Beats(447, Position.A);
	steps.add(beat);
	beat = new Beats(469, Position.A);
	steps.add(beat);
	beat = new Beats(512, Position.A);
	steps.add(beat);
	beat = new Beats(532, Position.A);
	steps.add(beat);
	beat = new Beats(555, Position.A);
	steps.add(beat);
	beat = new Beats(619, Position.A);
	steps.add(beat);
	beat = new Beats(641, Position.A);
	steps.add(beat);
	beat = new Beats(661, Position.A);
	steps.add(beat);
	beat = new Beats(681, Position.A);
	steps.add(beat);
	beat = new Beats(715, Position.A);
	steps.add(beat);
	beat = new Beats(727, Position.A);
	steps.add(beat);
	beat = new Beats(768, Position.A);
	steps.add(beat);
	beat = new Beats(821, Position.A);
	steps.add(beat);
	beat = new Beats(877, Position.A);
	steps.add(beat);
	beat = new Beats(1144, Position.A);
	steps.add(beat);
	beat = new Beats(1158, Position.A);
	steps.add(beat);
	beat = new Beats(1183, Position.A);
	steps.add(beat);
	beat = new Beats(1194, Position.A);
	steps.add(beat);
	beat = new Beats(1215, Position.A);
	steps.add(beat);
	beat = new Beats(1247, Position.A);
	steps.add(beat);
	beat = new Beats(1270, Position.A);
	steps.add(beat);
	beat = new Beats(1280, Position.A);
	steps.add(beat);
	beat = new Beats(1300, Position.A);
	steps.add(beat);
	beat = new Beats(1319, Position.A);
	steps.add(beat);
	beat = new Beats(1340, Position.A);
	steps.add(beat);
	beat = new Beats(1350, Position.A);
	steps.add(beat);
	beat = new Beats(1360, Position.A);
	steps.add(beat);
	beat = new Beats(1384, Position.A);
	steps.add(beat);
	beat = new Beats(1419, Position.A);
	steps.add(beat);
	beat = new Beats(1440, Position.A);
	steps.add(beat);
	beat = new Beats(1451, Position.A);
	steps.add(beat);
	beat = new Beats(1471, Position.A);
	steps.add(beat);
	beat = new Beats(1481, Position.A);
	steps.add(beat);
	beat = new Beats(1509, Position.A);
	steps.add(beat);
	beat = new Beats(1519, Position.A);
	steps.add(beat);
	beat = new Beats(1530, Position.A);
	steps.add(beat);
	beat = new Beats(1556, Position.A);
	steps.add(beat);
	beat = new Beats(1590, Position.A);
	steps.add(beat);
	beat = new Beats(1611, Position.A);
	steps.add(beat);
	beat = new Beats(1623, Position.A);
	steps.add(beat);
	beat = new Beats(1641, Position.A);
	steps.add(beat);
	beat = new Beats(1661, Position.A);
	steps.add(beat);
	beat = new Beats(1684, Position.A);
	steps.add(beat);
	beat = new Beats(1697, Position.A);
	steps.add(beat);
	beat = new Beats(1707, Position.A);
	steps.add(beat);
	beat = new Beats(1717, Position.A);
	steps.add(beat);
	beat = new Beats(1727, Position.A);
	steps.add(beat);
	beat = new Beats(1738, Position.A);
	steps.add(beat);
	beat = new Beats(1748, Position.A);
	steps.add(beat);
	beat = new Beats(1759, Position.A);
	steps.add(beat);
	beat = new Beats(1770, Position.A);
	steps.add(beat);
	beat = new Beats(1780, Position.A);
	steps.add(beat);
	beat = new Beats(1791, Position.A);
	steps.add(beat);
	beat = new Beats(1801, Position.A);
	steps.add(beat);
	beat = new Beats(1812, Position.A);
	steps.add(beat);
	beat = new Beats(1834, Position.A);
	steps.add(beat);
	beat = new Beats(1845, Position.A);
	steps.add(beat);
	beat = new Beats(1855, Position.A);
	steps.add(beat);
	beat = new Beats(1864, Position.A);
	steps.add(beat);
	beat = new Beats(1887, Position.A);
	steps.add(beat);
	beat = new Beats(1898, Position.A);
	steps.add(beat);
	beat = new Beats(1920, Position.A);
	steps.add(beat);
	beat = new Beats(1929, Position.A);
	steps.add(beat);
	beat = new Beats(1950, Position.A);
	steps.add(beat);
	beat = new Beats(1961, Position.A);
	steps.add(beat);
	beat = new Beats(1985, Position.A);
	steps.add(beat);
	beat = new Beats(2007, Position.A);
	steps.add(beat);
	beat = new Beats(2028, Position.A);
	steps.add(beat);
	beat = new Beats(2039, Position.A);
	steps.add(beat);
	beat = new Beats(2050, Position.A);
	steps.add(beat);
	beat = new Beats(2060, Position.A);
	steps.add(beat);
	beat = new Beats(2091, Position.A);
	steps.add(beat);
	beat = new Beats(2114, Position.A);
	steps.add(beat);
	beat = new Beats(2125, Position.A);
	steps.add(beat);
	beat = new Beats(2136, Position.A);
	steps.add(beat);
	beat = new Beats(2147, Position.A);
	steps.add(beat);
	beat = new Beats(2167, Position.A);
	steps.add(beat);
	beat = new Beats(2188, Position.A);
	steps.add(beat);
	beat = new Beats(2199, Position.A);
	steps.add(beat);
	beat = new Beats(2232, Position.A);
	steps.add(beat);
	beat = new Beats(2242, Position.A);
	steps.add(beat);
	beat = new Beats(2252, Position.A);
	steps.add(beat);
	beat = new Beats(2276, Position.A);
	steps.add(beat);
	beat = new Beats(2299, Position.A);
	steps.add(beat);
	beat = new Beats(2319, Position.A);
	steps.add(beat);
	beat = new Beats(2339, Position.A);
	steps.add(beat);
	beat = new Beats(2359, Position.A);
	steps.add(beat);
	beat = new Beats(2369, Position.A);
	steps.add(beat);
	beat = new Beats(2391, Position.A);
	steps.add(beat);
	beat = new Beats(2404, Position.A);
	steps.add(beat);
	beat = new Beats(2424, Position.A);
	steps.add(beat);
	beat = new Beats(2445, Position.A);
	steps.add(beat);
	beat = new Beats(2466, Position.A);
	steps.add(beat);
	beat = new Beats(2488, Position.A);
	steps.add(beat);
	beat = new Beats(2506, Position.A);
	steps.add(beat);
	beat = new Beats(2540, Position.A);
	steps.add(beat);
	beat = new Beats(2551, Position.A);
	steps.add(beat);
	beat = new Beats(2562, Position.A);
	steps.add(beat);
	beat = new Beats(2596, Position.A);
	steps.add(beat);
	beat = new Beats(2607, Position.A);
	steps.add(beat);
	beat = new Beats(2617, Position.A);
	steps.add(beat);
	beat = new Beats(2629, Position.A);
	steps.add(beat);
	beat = new Beats(2639, Position.A);
	steps.add(beat);
	beat = new Beats(2651, Position.A);
	steps.add(beat);
	beat = new Beats(2661, Position.A);
	steps.add(beat);
	beat = new Beats(2672, Position.A);
	steps.add(beat);
	beat = new Beats(2683, Position.A);
	steps.add(beat);
	beat = new Beats(2694, Position.A);
	steps.add(beat);
	beat = new Beats(2723, Position.A);
	steps.add(beat);
	beat = new Beats(2744, Position.A);
	steps.add(beat);
	beat = new Beats(2754, Position.A);
	steps.add(beat);
	beat = new Beats(2766, Position.A);
	steps.add(beat);
	beat = new Beats(2778, Position.A);
	steps.add(beat);
	beat = new Beats(2789, Position.A);
	steps.add(beat);
	beat = new Beats(2800, Position.A);
	steps.add(beat);
	beat = new Beats(2817, Position.A);
	steps.add(beat);
	beat = new Beats(2842, Position.A);
	steps.add(beat);
	beat = new Beats(2853, Position.A);
	steps.add(beat);
	beat = new Beats(2863, Position.A);
	steps.add(beat);
	beat = new Beats(2874, Position.A);
	steps.add(beat);
	beat = new Beats(2887, Position.A);
	steps.add(beat);
	beat = new Beats(2928, Position.A);
	steps.add(beat);
	beat = new Beats(2948, Position.A);
	steps.add(beat);
	beat = new Beats(2970, Position.A);
	steps.add(beat);
	beat = new Beats(2991, Position.A);
	steps.add(beat);
	beat = new Beats(3012, Position.A);
	steps.add(beat);
	beat = new Beats(3044, Position.A);
	steps.add(beat);
	beat = new Beats(3056, Position.A);
	steps.add(beat);
	beat = new Beats(3067, Position.A);
	steps.add(beat);
	beat = new Beats(3079, Position.A);
	steps.add(beat);
	beat = new Beats(3090, Position.A);
	steps.add(beat);
	beat = new Beats(3101, Position.A);
	steps.add(beat);
	beat = new Beats(3114, Position.A);
	steps.add(beat);
	beat = new Beats(3124, Position.A);
	steps.add(beat);
	beat = new Beats(3136, Position.A);
	steps.add(beat);
	beat = new Beats(3158, Position.A);
	steps.add(beat);
	beat = new Beats(3171, Position.A);
	steps.add(beat);
	beat = new Beats(3182, Position.A);
	steps.add(beat);
	beat = new Beats(3193, Position.A);
	steps.add(beat);
	beat = new Beats(3203, Position.A);
	steps.add(beat);
	beat = new Beats(3226, Position.A);
	steps.add(beat);
	beat = new Beats(3248, Position.A);
	steps.add(beat);
	beat = new Beats(3289, Position.A);
	steps.add(beat);
	beat = new Beats(3311, Position.A);
	steps.add(beat);
	beat = new Beats(3333, Position.A);
	steps.add(beat);
	beat = new Beats(3374, Position.A);
	steps.add(beat);
	beat = new Beats(3395, Position.A);
	steps.add(beat);
	beat = new Beats(3405, Position.A);
	steps.add(beat);
	beat = new Beats(3416, Position.A);
	steps.add(beat);
	beat = new Beats(3427, Position.A);
	steps.add(beat);
	beat = new Beats(3451, Position.A);
	steps.add(beat);
	beat = new Beats(3473, Position.A);
	steps.add(beat);
	beat = new Beats(3494, Position.A);
	steps.add(beat);
	beat = new Beats(3504, Position.A);
	steps.add(beat);
	beat = new Beats(3516, Position.A);
	steps.add(beat);
	beat = new Beats(3527, Position.A);
	steps.add(beat);
	beat = new Beats(3548, Position.A);
	steps.add(beat);
	beat = new Beats(3558, Position.A);
	steps.add(beat);
	beat = new Beats(3571, Position.A);
	steps.add(beat);
	beat = new Beats(3590, Position.A);
	steps.add(beat);
	beat = new Beats(3632, Position.A);
	steps.add(beat);
	beat = new Beats(3653, Position.A);
	steps.add(beat);
	beat = new Beats(3675, Position.A);
	steps.add(beat);
	beat = new Beats(3719, Position.A);
	steps.add(beat);
	beat = new Beats(3740, Position.A);
	steps.add(beat);
	beat = new Beats(3761, Position.A);
	steps.add(beat);
	beat = new Beats(3781, Position.A);
	steps.add(beat);
	beat = new Beats(3804, Position.A);
	steps.add(beat);
	beat = new Beats(3824, Position.A);
	steps.add(beat);
	beat = new Beats(3847, Position.A);
	steps.add(beat);
	beat = new Beats(3868, Position.A);
	steps.add(beat);
	beat = new Beats(3888, Position.A);
	steps.add(beat);
	beat = new Beats(3910, Position.A);
	steps.add(beat);
	beat = new Beats(3920, Position.A);
	steps.add(beat);
	beat = new Beats(3932, Position.A);
	steps.add(beat);
	beat = new Beats(3954, Position.A);
	steps.add(beat);
	beat = new Beats(3976, Position.A);
	steps.add(beat);
	beat = new Beats(3987, Position.A);
	steps.add(beat);
	beat = new Beats(4007, Position.A);
	steps.add(beat);
	beat = new Beats(4017, Position.A);
	steps.add(beat);
	beat = new Beats(4038, Position.A);
	steps.add(beat);
	beat = new Beats(4060, Position.A);
	steps.add(beat);
	beat = new Beats(4082, Position.A);
	steps.add(beat);
	beat = new Beats(4140, Position.A);
	steps.add(beat);
	beat = new Beats(4155, Position.A);
	steps.add(beat);
	beat = new Beats(4196, Position.A);
	steps.add(beat);
	beat = new Beats(4208, Position.A);
	steps.add(beat);
	beat = new Beats(4231, Position.A);
	steps.add(beat);
	beat = new Beats(4242, Position.A);
	steps.add(beat);
	beat = new Beats(4255, Position.A);
	steps.add(beat);
	beat = new Beats(4274, Position.A);
	steps.add(beat);
	beat = new Beats(4295, Position.A);
	steps.add(beat);
	beat = new Beats(4316, Position.A);
	steps.add(beat);
	beat = new Beats(4337, Position.A);
	steps.add(beat);
	beat = new Beats(4382, Position.A);
	steps.add(beat);
	beat = new Beats(4404, Position.A);
	steps.add(beat);
	beat = new Beats(4425, Position.A);
	steps.add(beat);
	beat = new Beats(4473, Position.A);
	steps.add(beat);
	beat = new Beats(4495, Position.A);
	steps.add(beat);
	beat = new Beats(4509, Position.A);
	steps.add(beat);
	beat = new Beats(4529, Position.A);
	steps.add(beat);
	beat = new Beats(4550, Position.A);
	steps.add(beat);
	beat = new Beats(4585, Position.A);
	steps.add(beat);
	beat = new Beats(4596, Position.A);
	steps.add(beat);
	beat = new Beats(4608, Position.A);
	steps.add(beat);
	beat = new Beats(4619, Position.A);
	steps.add(beat);
	beat = new Beats(4631, Position.A);
	steps.add(beat);
	beat = new Beats(4643, Position.A);
	steps.add(beat);
	beat = new Beats(4657, Position.A);
	steps.add(beat);
	beat = new Beats(4669, Position.A);
	steps.add(beat);
	beat = new Beats(4679, Position.A);
	steps.add(beat);
	beat = new Beats(4719, Position.A);
	steps.add(beat);
	beat = new Beats(4745, Position.A);
	steps.add(beat);
	beat = new Beats(4766, Position.A);
	steps.add(beat);
	beat = new Beats(4821, Position.A);
	steps.add(beat);
	beat = new Beats(4836, Position.A);
	steps.add(beat);
	beat = new Beats(4882, Position.A);
	steps.add(beat);
	beat = new Beats(4895, Position.A);
	steps.add(beat);
	beat = new Beats(4908, Position.A);
	steps.add(beat);
	beat = new Beats(4918, Position.A);
	steps.add(beat);
	beat = new Beats(4930, Position.A);
	steps.add(beat);
	beat = new Beats(4939, Position.A);
	steps.add(beat);
	beat = new Beats(4959, Position.A);
	steps.add(beat);
	beat = new Beats(4979, Position.A);
	steps.add(beat);
	beat = new Beats(5000, Position.A);
	steps.add(beat);
	beat = new Beats(5021, Position.A);
	steps.add(beat);
	beat = new Beats(5065, Position.A);
	steps.add(beat);
	beat = new Beats(5087, Position.A);
	steps.add(beat);
	beat = new Beats(5109, Position.A);
	steps.add(beat);
	beat = new Beats(5172, Position.A);
	steps.add(beat);
	beat = new Beats(5188, Position.A);
	steps.add(beat);
	beat = new Beats(5271, Position.A);
	steps.add(beat);
	beat = new Beats(5282, Position.A);
	steps.add(beat);
	beat = new Beats(5292, Position.A);
	steps.add(beat);
	beat = new Beats(5305, Position.A);
	steps.add(beat);
	beat = new Beats(5315, Position.A);
	steps.add(beat);
	beat = new Beats(5326, Position.A);
	steps.add(beat);
	beat = new Beats(5348, Position.A);
	steps.add(beat);
	beat = new Beats(5361, Position.A);
	steps.add(beat);
	beat = new Beats(5399, Position.A);
	steps.add(beat);
	beat = new Beats(5409, Position.A);
	steps.add(beat);
	beat = new Beats(5489, Position.A);
	steps.add(beat);
	beat = new Beats(5499, Position.A);
	steps.add(beat);
	beat = new Beats(5509, Position.A);
	steps.add(beat);
	beat = new Beats(5519, Position.A);
	steps.add(beat);
	beat = new Beats(5530, Position.A);
	steps.add(beat);
	beat = new Beats(5544, Position.A);
	steps.add(beat);
	beat = new Beats(5554, Position.A);
	steps.add(beat);
	beat = new Beats(5563, Position.A);
	steps.add(beat);
	beat = new Beats(5581, Position.A);
	steps.add(beat);
	beat = new Beats(5611, Position.A);
	steps.add(beat);
	beat = new Beats(5632, Position.A);
	steps.add(beat);
	beat = new Beats(5643, Position.A);
	steps.add(beat);
	beat = new Beats(5664, Position.A);
	steps.add(beat);
	beat = new Beats(5682, Position.A);
	steps.add(beat);
	beat = new Beats(5706, Position.A);
	steps.add(beat);
	beat = new Beats(5716, Position.A);
	steps.add(beat);
	beat = new Beats(5727, Position.A);
	steps.add(beat);
	beat = new Beats(5749, Position.A);
	steps.add(beat);
	beat = new Beats(5782, Position.A);
	steps.add(beat);
	beat = new Beats(5801, Position.A);
	steps.add(beat);
	beat = new Beats(5811, Position.A);
	steps.add(beat);
	beat = new Beats(5832, Position.A);
	steps.add(beat);
	beat = new Beats(5851, Position.A);
	steps.add(beat);
	beat = new Beats(5874, Position.A);
	steps.add(beat);
	beat = new Beats(5886, Position.A);
	steps.add(beat);
	beat = new Beats(5896, Position.A);
	steps.add(beat);
	beat = new Beats(5919, Position.A);
	steps.add(beat);
	beat = new Beats(5954, Position.A);
	steps.add(beat);
	beat = new Beats(5974, Position.A);
	steps.add(beat);
	beat = new Beats(5984, Position.A);
	steps.add(beat);
	beat = new Beats(6013, Position.A);
	steps.add(beat);
	beat = new Beats(6025, Position.A);
	steps.add(beat);
  }
  
  @Override
  protected void setVariables() {
	song = "/rules/BeatIt/Music/Hatsune Miku - World Is Mine.wav";
	pads = "/rules/BeatIt/BeatItImages/GreyStar-Image.png";
	beats = "/rules/BeatIt/BeatItImages/BlueStar-Image.png";
	background = "/rules/BeatIt/BeatItImages/Hatsune-Miku-Background.jpg";
	duration = 6200;
  }
  
//  public static void main(String[] args) {
//	Song song = new Hatsune_Miku_World_Is_Mine();
//	song.print();
//  }

}
