package rules.BeatIt.Songs;

import rules.BeatIt.Beats;
import rules.BeatIt.Beats.Position;

public class Hatsune_Miku_World_Is_Mine extends Song{
  
  public Hatsune_Miku_World_Is_Mine() { // Maybe add argument if you want to adjust difficulty or speed?
	populateSteps();
	setVariables();
  }

  @Override
  protected void populateSteps() {
	Beats beat = new Beats(196, Position.A);
	steps.add(beat);
	beat = new Beats(215, Position.S);
	steps.add(beat);
	beat = new Beats(278, Position.L);
	steps.add(beat);
	beat = new Beats(330, Position.SPACE);
	steps.add(beat);
	beat = new Beats(342, Position.S);
	steps.add(beat);
	beat = new Beats(360, Position.K);
	steps.add(beat);
	beat = new Beats(369, Position.L);
	steps.add(beat);
	beat = new Beats(384, Position.S);
	steps.add(beat);
	beat = new Beats(402, Position.SPACE);
	steps.add(beat);
	beat = new Beats(422, Position.K);
	steps.add(beat);
	beat = new Beats(446, Position.A);
	steps.add(beat);
	beat = new Beats(467, Position.SPACE);
	steps.add(beat);
	beat = new Beats(510, Position.K);
	steps.add(beat);
	beat = new Beats(530, Position.S);
	steps.add(beat);
	beat = new Beats(550, Position.SPACE);
	steps.add(beat);
	beat = new Beats(613, Position.L);
	steps.add(beat);
	beat = new Beats(634, Position.A);
	steps.add(beat);
	beat = new Beats(653, Position.SPACE);
	steps.add(beat);
	beat = new Beats(676, Position.S);
	steps.add(beat);
	beat = new Beats(706, Position.K);
	steps.add(beat);
	beat = new Beats(717, Position.L);
	steps.add(beat);
	beat = new Beats(747, Position.SPACE);
	steps.add(beat);
	beat = new Beats(761, Position.S);
	steps.add(beat);
	beat = new Beats(816, Position.K);
	steps.add(beat);
	beat = new Beats(869, Position.SPACE);
	steps.add(beat);
	beat = new Beats(1127, Position.L);
	steps.add(beat);
	beat = new Beats(1142, Position.A);
	steps.add(beat);
	beat = new Beats(1150, Position.K);
	steps.add(beat);
	beat = new Beats(1201, Position.SPACE);
	steps.add(beat);
	beat = new Beats(1228, Position.K);
	steps.add(beat);
	beat = new Beats(1250, Position.K);
	steps.add(beat);
	beat = new Beats(1262, Position.S);
	steps.add(beat);
	beat = new Beats(1281, Position.L);
	steps.add(beat);
	beat = new Beats(1302, Position.K);
	steps.add(beat);
	beat = new Beats(1324, Position.A);
	steps.add(beat);
	beat = new Beats(1333, Position.L);
	steps.add(beat);
	beat = new Beats(1343, Position.S);
	steps.add(beat);
	beat = new Beats(1351, Position.K);
	steps.add(beat);
	beat = new Beats(1366, Position.SPACE);
	steps.add(beat);
	beat = new Beats(1401, Position.L);
	steps.add(beat);
	beat = new Beats(1420, Position.A);
	steps.add(beat);
	beat = new Beats(1429, Position.K);
	steps.add(beat);
	beat = new Beats(1449, Position.S);
	steps.add(beat);
	beat = new Beats(1467, Position.SPACE);
	steps.add(beat);
	beat = new Beats(1489, Position.A);
	steps.add(beat);
	beat = new Beats(1506, Position.S);
	steps.add(beat);
	beat = new Beats(1515, Position.K);
	steps.add(beat);
	beat = new Beats(1531, Position.SPACE);
	steps.add(beat);
	beat = new Beats(1566, Position.L);
	steps.add(beat);
	beat = new Beats(1585, Position.A);
	steps.add(beat);
	beat = new Beats(1594, Position.K);
	steps.add(beat);
	beat = new Beats(1617, Position.S);
	steps.add(beat);
	beat = new Beats(1636, Position.L);
	steps.add(beat);
	beat = new Beats(1660, Position.A);
	steps.add(beat);
	beat = new Beats(1671, Position.S);
	steps.add(beat);
	beat = new Beats(1683, Position.SPACE);
	steps.add(beat);
	beat = new Beats(1693, Position.K);
	steps.add(beat);
	beat = new Beats(1702, Position.L);
	steps.add(beat);
	beat = new Beats(1711, Position.A);
	steps.add(beat);
	beat = new Beats(1725, Position.S);
	steps.add(beat);
	beat = new Beats(1734, Position.SPACE);
	steps.add(beat);
	beat = new Beats(1745, Position.K);
	steps.add(beat);
	beat = new Beats(1755, Position.L);
	steps.add(beat);
	beat = new Beats(1765, Position.A);
	steps.add(beat);
	beat = new Beats(1777, Position.SPACE);
	steps.add(beat);
	beat = new Beats(1784, Position.S);
	steps.add(beat);
	beat = new Beats(1798, Position.K);
	steps.add(beat);
	beat = new Beats(1805, Position.L);
	steps.add(beat);
	beat = new Beats(1816, Position.S);
	steps.add(beat);
	beat = new Beats(1826, Position.K);
	steps.add(beat);
	beat = new Beats(1836, Position.SPACE);
	steps.add(beat);
	beat = new Beats(1856, Position.L);
	steps.add(beat);
	beat = new Beats(1865, Position.A);
	steps.add(beat);
	beat = new Beats(1888, Position.K);
	steps.add(beat);
	beat = new Beats(1898, Position.S);
	steps.add(beat);
	beat = new Beats(1919, Position.SPACE);
	steps.add(beat);
	beat = new Beats(1928, Position.L);
	steps.add(beat);
	beat = new Beats(1952, Position.S);
	steps.add(beat);
	beat = new Beats(1973, Position.K);
	steps.add(beat);
	beat = new Beats(1992, Position.A);
	steps.add(beat);
	beat = new Beats(2000, Position.SPACE);
	steps.add(beat);
	beat = new Beats(2007, Position.S);
	steps.add(beat);
	beat = new Beats(2014, Position.L);
	steps.add(beat);
	beat = new Beats(2025, Position.K);
	steps.add(beat);
	beat = new Beats(2051, Position.SPACE);
	steps.add(beat);
	beat = new Beats(2073, Position.L);
	steps.add(beat);
	beat = new Beats(2081, Position.S);
	steps.add(beat);
	beat = new Beats(2088, Position.K);
	steps.add(beat);
	beat = new Beats(2099, Position.A);
	steps.add(beat);
	beat = new Beats(2108, Position.SPACE);
	steps.add(beat);
	beat = new Beats(2126, Position.S);
	steps.add(beat);
	beat = new Beats(2146, Position.L);
	steps.add(beat);
	beat = new Beats(2154, Position.A);
	steps.add(beat);
	beat = new Beats(2191, Position.K);
	steps.add(beat);
	beat = new Beats(2198, Position.S);
	steps.add(beat);
	beat = new Beats(2206, Position.SPACE);
	steps.add(beat);
	beat = new Beats(2232, Position.L);
	steps.add(beat);
	beat = new Beats(2257, Position.K);
	steps.add(beat);
	beat = new Beats(2275, Position.S);
	steps.add(beat);
	beat = new Beats(2290, Position.L);
	steps.add(beat);
	beat = new Beats(2310, Position.A);
	steps.add(beat);
	beat = new Beats(2318, Position.K);
	steps.add(beat);
	beat = new Beats(2340, Position.S);
	steps.add(beat);
	beat = new Beats(2354, Position.SPACE);
	steps.add(beat);
	beat = new Beats(2371, Position.A);
	steps.add(beat);
	beat = new Beats(2393, Position.K);
	steps.add(beat);
	beat = new Beats(2414, Position.S);
	steps.add(beat);
	beat = new Beats(2434, Position.L);
	steps.add(beat);
	beat = new Beats(2464, Position.K);
	steps.add(beat);
	beat = new Beats(2493, Position.L);
	steps.add(beat);
	beat = new Beats(2501, Position.K);
	steps.add(beat);
	beat = new Beats(2513, Position.L);
	steps.add(beat);
	beat = new Beats(2541, Position.L);
	steps.add(beat);
	beat = new Beats(2552, Position.L);
	steps.add(beat);
	beat = new Beats(2562, Position.K);
	steps.add(beat);
	beat = new Beats(2576, Position.S);
	steps.add(beat);
	beat = new Beats(2583, Position.SPACE);
	steps.add(beat);
	beat = new Beats(2595, Position.A);
	steps.add(beat);
	beat = new Beats(2606, Position.SPACE);
	steps.add(beat);
	beat = new Beats(2618, Position.S);
	steps.add(beat);
	beat = new Beats(2628, Position.SPACE);
	steps.add(beat);
	beat = new Beats(2638, Position.S);
	steps.add(beat);
	beat = new Beats(2664, Position.K);
	steps.add(beat);
	beat = new Beats(2690, Position.A);
	steps.add(beat);
	beat = new Beats(2699, Position.L);
	steps.add(beat);
	beat = new Beats(2712, Position.S);
	steps.add(beat);
	beat = new Beats(2722, Position.K);
	steps.add(beat);
	beat = new Beats(2733, Position.SPACE);
	steps.add(beat);
	beat = new Beats(2745, Position.A);
	steps.add(beat);
	beat = new Beats(2765, Position.L);
	steps.add(beat);
	beat = new Beats(2787, Position.S);
	steps.add(beat);
	beat = new Beats(2794, Position.K);
	steps.add(beat);
	beat = new Beats(2805, Position.A);
	steps.add(beat);
	beat = new Beats(2814, Position.SPACE);
	steps.add(beat);
	beat = new Beats(2821, Position.S);
	steps.add(beat);
	beat = new Beats(2831, Position.K);
	steps.add(beat);
	beat = new Beats(2869, Position.L);
	steps.add(beat);
	beat = new Beats(2891, Position.L);
	steps.add(beat);
	beat = new Beats(2910, Position.K);
	steps.add(beat);
	beat = new Beats(2930, Position.SPACE);
	steps.add(beat);
	beat = new Beats(2955, Position.S);
	steps.add(beat);
	beat = new Beats(2985, Position.K);
	steps.add(beat);
	beat = new Beats(2994, Position.S);
	steps.add(beat);
	beat = new Beats(3011, Position.L);
	steps.add(beat);
	beat = new Beats(3019, Position.K);
	steps.add(beat);
	beat = new Beats(3041, Position.S);
	steps.add(beat);
	beat = new Beats(3051, Position.K);
	steps.add(beat);
	beat = new Beats(3062, Position.S);
	steps.add(beat);
	beat = new Beats(3071, Position.K);
	steps.add(beat);
	beat = new Beats(3096, Position.S);
	steps.add(beat);
	beat = new Beats(3108, Position.L);
	steps.add(beat);
	beat = new Beats(3121, Position.A);
	steps.add(beat);
	beat = new Beats(3139, Position.S);
	steps.add(beat);
	beat = new Beats(3163, Position.SPACE);
	steps.add(beat);
	beat = new Beats(3185, Position.SPACE);
	steps.add(beat);
	beat = new Beats(3224, Position.K);
	steps.add(beat);
	beat = new Beats(3248, Position.A);
	steps.add(beat);
	beat = new Beats(3267, Position.L);
	steps.add(beat);
	beat = new Beats(3312, Position.K);
	steps.add(beat);
	beat = new Beats(3331, Position.S);
	steps.add(beat);
	beat = new Beats(3338, Position.L);
	steps.add(beat);
	beat = new Beats(3349, Position.K);
	steps.add(beat);
	beat = new Beats(3365, Position.SPACE);
	steps.add(beat);
	beat = new Beats(3383, Position.A);
	steps.add(beat);
	beat = new Beats(3403, Position.SPACE);
	steps.add(beat);
	beat = new Beats(3423, Position.S);
	steps.add(beat);
	beat = new Beats(3433, Position.K);
	steps.add(beat);
	beat = new Beats(3444, Position.A);
	steps.add(beat);
	beat = new Beats(3453, Position.L);
	steps.add(beat);
	beat = new Beats(3476, Position.S);
	steps.add(beat);
	beat = new Beats(3486, Position.K);
	steps.add(beat);
	beat = new Beats(3495, Position.L);
	steps.add(beat);
	beat = new Beats(3505, Position.K);
	steps.add(beat);
	beat = new Beats(3522, Position.SPACE);
	steps.add(beat);
	beat = new Beats(3562, Position.K);
	steps.add(beat);
	beat = new Beats(3583, Position.S);
	steps.add(beat);
	beat = new Beats(3604, Position.SPACE);
	steps.add(beat);
	beat = new Beats(3650, Position.SPACE);
	steps.add(beat);
	beat = new Beats(3668, Position.A);
	steps.add(beat);
	beat = new Beats(3686, Position.L);
	steps.add(beat);
	beat = new Beats(3707, Position.S);
	steps.add(beat);
	beat = new Beats(3728, Position.K);
	steps.add(beat);
	beat = new Beats(3751, Position.K);
	steps.add(beat);
	beat = new Beats(3773, Position.K);
	steps.add(beat);
	beat = new Beats(3794, Position.K);
	steps.add(beat);
	beat = new Beats(3815, Position.K);
	steps.add(beat);
	beat = new Beats(3834, Position.L);
	steps.add(beat);
	beat = new Beats(3846, Position.A);
	steps.add(beat);
	beat = new Beats(3857, Position.K);
	steps.add(beat);
	beat = new Beats(3875, Position.SPACE);
	steps.add(beat);
	beat = new Beats(3898, Position.S);
	steps.add(beat);
	beat = new Beats(3911, Position.S);
	steps.add(beat);
	beat = new Beats(3930, Position.S);
	steps.add(beat);
	beat = new Beats(3941, Position.S);
	steps.add(beat);
	beat = new Beats(3962, Position.S);
	steps.add(beat);
	beat = new Beats(3982, Position.SPACE);
	steps.add(beat);
	beat = new Beats(4003, Position.A);
	steps.add(beat);
	beat = new Beats(4066, Position.L);
	steps.add(beat);
	beat = new Beats(4075, Position.K);
	steps.add(beat);
	beat = new Beats(4118, Position.A);
	steps.add(beat);
	beat = new Beats(4132, Position.S);
	steps.add(beat);
	beat = new Beats(4151, Position.SPACE);
	steps.add(beat);
	beat = new Beats(4162, Position.K);
	steps.add(beat);
	beat = new Beats(4171, Position.L);
	steps.add(beat);
	beat = new Beats(4192, Position.A);
	steps.add(beat);
	beat = new Beats(4213, Position.SPACE);
	steps.add(beat);
	beat = new Beats(4234, Position.S);
	steps.add(beat);
	beat = new Beats(4254, Position.K);
	steps.add(beat);
	beat = new Beats(4299, Position.A);
	steps.add(beat);
	beat = new Beats(4320, Position.L);
	steps.add(beat);
	beat = new Beats(4341, Position.S);
	steps.add(beat);
	beat = new Beats(4381, Position.K);
	steps.add(beat);
	beat = new Beats(4408, Position.L);
	steps.add(beat);
	beat = new Beats(4426, Position.K);
	steps.add(beat);
	beat = new Beats(4443, Position.L);
	steps.add(beat);
	beat = new Beats(4463, Position.SPACE);
	steps.add(beat);
	beat = new Beats(4501, Position.L);
	steps.add(beat);
	beat = new Beats(4511, Position.SPACE);
	steps.add(beat);
	beat = new Beats(4522, Position.K);
	steps.add(beat);
	beat = new Beats(4532, Position.SPACE);
	steps.add(beat);
	beat = new Beats(4542, Position.L);
	steps.add(beat);
	beat = new Beats(4553, Position.K);
	steps.add(beat);
	beat = new Beats(4565, Position.SPACE);
	steps.add(beat);
	beat = new Beats(4571, Position.L);
	steps.add(beat);
	beat = new Beats(4581, Position.K);
	steps.add(beat);
	beat = new Beats(4590, Position.SPACE);
	steps.add(beat);
	beat = new Beats(4624, Position.K);
	steps.add(beat);
	beat = new Beats(4650, Position.S);
	steps.add(beat);
	beat = new Beats(4662, Position.L);
	steps.add(beat);
	beat = new Beats(4682, Position.A);
	steps.add(beat);
	beat = new Beats(4720, Position.SPACE);
	steps.add(beat);
	beat = new Beats(4736, Position.S);
	steps.add(beat);
	beat = new Beats(4773, Position.K);
	steps.add(beat);
	beat = new Beats(4784, Position.S);
	steps.add(beat);
	beat = new Beats(4793, Position.SPACE);
	steps.add(beat);
	beat = new Beats(4803, Position.A);
	steps.add(beat);
	beat = new Beats(4812, Position.SPACE);
	steps.add(beat);
	beat = new Beats(4823, Position.S);
	steps.add(beat);
	beat = new Beats(4844, Position.K);
	steps.add(beat);
	beat = new Beats(4867, Position.L);
	steps.add(beat);
	beat = new Beats(4889, Position.A);
	steps.add(beat);
	beat = new Beats(4908, Position.L);
	steps.add(beat);
	beat = new Beats(4949, Position.K);
	steps.add(beat);
	beat = new Beats(4971, Position.S);
	steps.add(beat);
	beat = new Beats(4995, Position.SPACE);
	steps.add(beat);
	beat = new Beats(5059, Position.K);
	steps.add(beat);
	beat = new Beats(5078, Position.S);
	steps.add(beat);
	beat = new Beats(5147, Position.L);
	steps.add(beat);
	beat = new Beats(5161, Position.A);
	steps.add(beat);
	beat = new Beats(5172, Position.K);
	steps.add(beat);
	beat = new Beats(5183, Position.S);
	steps.add(beat);
	beat = new Beats(5190, Position.SPACE);
	steps.add(beat);
	beat = new Beats(5200, Position.A);
	steps.add(beat);
	beat = new Beats(5211, Position.L);
	steps.add(beat);
	beat = new Beats(5232, Position.S);
	steps.add(beat);
	beat = new Beats(5241, Position.K);
	steps.add(beat);
	beat = new Beats(5250, Position.A);
	steps.add(beat);
	beat = new Beats(5285, Position.SPACE);
	steps.add(beat);
	beat = new Beats(5293, Position.S);
	steps.add(beat);
	beat = new Beats(5371, Position.L);
	steps.add(beat);
	beat = new Beats(5379, Position.S);
	steps.add(beat);
	beat = new Beats(5387, Position.K);
	steps.add(beat);
	beat = new Beats(5397, Position.S);
	steps.add(beat);
	beat = new Beats(5404, Position.SPACE);
	steps.add(beat);
	beat = new Beats(5412, Position.S);
	steps.add(beat);
	beat = new Beats(5492, Position.K);
	steps.add(beat);
	beat = new Beats(5513, Position.K);
	steps.add(beat);
	beat = new Beats(5524, Position.K);
	steps.add(beat);
	beat = new Beats(5542, Position.S);
	steps.add(beat);
	beat = new Beats(5560, Position.L);
	steps.add(beat);
	beat = new Beats(5586, Position.A);
	steps.add(beat);
	beat = new Beats(5596, Position.K);
	steps.add(beat);
	beat = new Beats(5606, Position.S);
	steps.add(beat);
	beat = new Beats(5626, Position.L);
	steps.add(beat);
	beat = new Beats(5659, Position.K);
	steps.add(beat);
	beat = new Beats(5681, Position.S);
	steps.add(beat);
	beat = new Beats(5690, Position.L);
	steps.add(beat);
	beat = new Beats(5711, Position.A);
	steps.add(beat);
	beat = new Beats(5730, Position.K);
	steps.add(beat);
	beat = new Beats(5752, Position.L);
	steps.add(beat);
	beat = new Beats(5765, Position.S);
	steps.add(beat);
	beat = new Beats(5774, Position.K);
	steps.add(beat);
	beat = new Beats(5796, Position.S);
	steps.add(beat);
	beat = new Beats(5825, Position.L);
	steps.add(beat);
	beat = new Beats(5846, Position.A);
	steps.add(beat);
	beat = new Beats(5856, Position.K);
	steps.add(beat);
	beat = new Beats(5875, Position.S);
	steps.add(beat);
	beat = new Beats(5898, Position.SPACE);
	steps.add(beat);
  }
  
  @Override
  protected void setVariables() {
	song = "/rules/BeatIt/Music/Hatsune Miku - World Is Mine.wav";
	pads = "/rules/BeatIt/BeatItImages/GreyStar-Image.png";
	beats = "/rules/BeatIt/BeatItImages/BlueStar-Image.png";
	background = "/rules/BeatIt/BeatItImages/Hatsune-Miku-Background.jpg";
	duration = 6000;
  }
  
//  public static void main(String[] args) {
//	Song song = new Hatsune_Miku_World_Is_Mine();
//	song.print();
//  }

}
