package rules.BeatIt.Songs;

import rules.BeatIt.Beats;
import rules.BeatIt.Beats.Position;


public class Hatsune_Miku_World_Is_Mine extends Song{
  
  public Hatsune_Miku_World_Is_Mine() { // Maybe add argument if you want to adjust difficulty or speed?
	populateSteps();
	setVariables();
  }

  @Override
  protected void populateSteps() {
	Beats beat = new Beats(196, Position.A);
	steps.add(beat);
	beat = new Beats(219, Position.L);
	steps.add(beat);
	beat = new Beats(283, Position.K);
	steps.add(beat);
	beat = new Beats(294, Position.S);
	steps.add(beat);
	beat = new Beats(333, Position.L);
	steps.add(beat);
	beat = new Beats(344, Position.A);
	steps.add(beat);
	beat = new Beats(362, Position.K);
	steps.add(beat);
	beat = new Beats(372, Position.K);
	steps.add(beat);
	beat = new Beats(384, Position.SPACE);
	steps.add(beat);
	beat = new Beats(407, Position.S);
	steps.add(beat);
	beat = new Beats(428, Position.A);
	steps.add(beat);
	beat = new Beats(454, Position.A);
	steps.add(beat);
	beat = new Beats(474, Position.S);
	steps.add(beat);
	beat = new Beats(519, Position.SPACE);
	steps.add(beat);
	beat = new Beats(540, Position.S);
	steps.add(beat);
	beat = new Beats(560, Position.L);
	steps.add(beat);
	beat = new Beats(620, Position.K);
	steps.add(beat);
	beat = new Beats(642, Position.S);
	steps.add(beat);
	beat = new Beats(662, Position.SPACE);
	steps.add(beat);
	beat = new Beats(686, Position.A);
	steps.add(beat);
	beat = new Beats(718, Position.S);
	steps.add(beat);
	beat = new Beats(730, Position.S);
	steps.add(beat);
	beat = new Beats(760, Position.L);
	steps.add(beat);
	beat = new Beats(774, Position.K);
	steps.add(beat);
	beat = new Beats(824, Position.SPACE);
	steps.add(beat);
	beat = new Beats(879, Position.A);
	steps.add(beat);
	beat = new Beats(1152, Position.L);
	steps.add(beat);
	beat = new Beats(1164, Position.S);
	steps.add(beat);
	beat = new Beats(1173, Position.K);
	steps.add(beat);
	beat = new Beats(1218, Position.SPACE);
	steps.add(beat);
	beat = new Beats(1249, Position.L);
	steps.add(beat);
	beat = new Beats(1267, Position.L);
	steps.add(beat);
	beat = new Beats(1279, Position.L);
	steps.add(beat);
	beat = new Beats(1303, Position.K);
	steps.add(beat);
	beat = new Beats(1324, Position.S);
	steps.add(beat);
	beat = new Beats(1343, Position.SPACE);
	steps.add(beat);
	beat = new Beats(1355, Position.SPACE);
	steps.add(beat);
	beat = new Beats(1365, Position.SPACE);
	steps.add(beat);
	beat = new Beats(1385, Position.S);
	steps.add(beat);
	beat = new Beats(1422, Position.L);
	steps.add(beat);
	beat = new Beats(1442, Position.L);
	steps.add(beat);
	beat = new Beats(1453, Position.L);
	steps.add(beat);
	beat = new Beats(1473, Position.K);
	steps.add(beat);
	beat = new Beats(1482, Position.SPACE);
	steps.add(beat);
	beat = new Beats(1517, Position.A);
	steps.add(beat);
	beat = new Beats(1529, Position.A);
	steps.add(beat);
	beat = new Beats(1539, Position.A);
	steps.add(beat);
	beat = new Beats(1561, Position.S);
	steps.add(beat);
	beat = new Beats(1594, Position.A);
	steps.add(beat);
	beat = new Beats(1613, Position.A);
	steps.add(beat);
	beat = new Beats(1625, Position.A);
	steps.add(beat);
	beat = new Beats(1645, Position.S);
	steps.add(beat);
	beat = new Beats(1668, Position.SPACE);
	steps.add(beat);
	beat = new Beats(1689, Position.L);
	steps.add(beat);
	beat = new Beats(1709, Position.SPACE);
	steps.add(beat);
	beat = new Beats(1721, Position.S);
	steps.add(beat);
	beat = new Beats(1744, Position.L);
	steps.add(beat);
	beat = new Beats(1764, Position.SPACE);
	steps.add(beat);
	beat = new Beats(1776, Position.S);
	steps.add(beat);
	beat = new Beats(1795, Position.L);
	steps.add(beat);
	beat = new Beats(1816, Position.SPACE);
	steps.add(beat);
	beat = new Beats(1839, Position.SPACE);
	steps.add(beat);
	beat = new Beats(1849, Position.S);
	steps.add(beat);
	beat = new Beats(1859, Position.K);
	steps.add(beat);
	beat = new Beats(1868, Position.S);
	steps.add(beat);
	beat = new Beats(1890, Position.K);
	steps.add(beat);
	beat = new Beats(1901, Position.K);
	steps.add(beat);
	beat = new Beats(1924, Position.S);
	steps.add(beat);
	beat = new Beats(1936, Position.L);
	steps.add(beat);
	beat = new Beats(1957, Position.A);
	steps.add(beat);
	beat = new Beats(1969, Position.A);
	steps.add(beat);
	beat = new Beats(1990, Position.A);
	steps.add(beat);
	beat = new Beats(2010, Position.S);
	steps.add(beat);
	beat = new Beats(2030, Position.A);
	steps.add(beat);
	beat = new Beats(2043, Position.S);
	steps.add(beat);
	beat = new Beats(2052, Position.A);
	steps.add(beat);
	beat = new Beats(2063, Position.S);
	steps.add(beat);
	beat = new Beats(2094, Position.SPACE);
	steps.add(beat);
	beat = new Beats(2115, Position.K);
	steps.add(beat);
	beat = new Beats(2124, Position.L);
	steps.add(beat);
	beat = new Beats(2136, Position.S);
	steps.add(beat);
	beat = new Beats(2150, Position.K);
	steps.add(beat);
	beat = new Beats(2171, Position.SPACE);
	steps.add(beat);
	beat = new Beats(2189, Position.L);
	steps.add(beat);
	beat = new Beats(2201, Position.K);
	steps.add(beat);
	beat = new Beats(2234, Position.L);
	steps.add(beat);
	beat = new Beats(2246, Position.K);
	steps.add(beat);
	beat = new Beats(2258, Position.SPACE);
	steps.add(beat);
	beat = new Beats(2278, Position.L);
	steps.add(beat);
	beat = new Beats(2299, Position.K);
	steps.add(beat);
	beat = new Beats(2320, Position.S);
	steps.add(beat);
	beat = new Beats(2340, Position.SPACE);
	steps.add(beat);
	beat = new Beats(2364, Position.A);
	steps.add(beat);
	beat = new Beats(2371, Position.L);
	steps.add(beat);
	beat = new Beats(2395, Position.S);
	steps.add(beat);
	beat = new Beats(2407, Position.K);
	steps.add(beat);
	beat = new Beats(2425, Position.SPACE);
	steps.add(beat);
	beat = new Beats(2450, Position.A);
	steps.add(beat);
	beat = new Beats(2468, Position.K);
	steps.add(beat);
	beat = new Beats(2488, Position.S);
	steps.add(beat);
	beat = new Beats(2511, Position.SPACE);
	steps.add(beat);
	beat = new Beats(2545, Position.L);
	steps.add(beat);
	beat = new Beats(2558, Position.L);
	steps.add(beat);
	beat = new Beats(2569, Position.L);
	steps.add(beat);
	beat = new Beats(2597, Position.K);
	steps.add(beat);
	beat = new Beats(2610, Position.S);
	steps.add(beat);
	beat = new Beats(2619, Position.SPACE);
	steps.add(beat);
	beat = new Beats(2630, Position.A);
	steps.add(beat);
	beat = new Beats(2643, Position.SPACE);
	steps.add(beat);
	beat = new Beats(2654, Position.S);
	steps.add(beat);
	beat = new Beats(2665, Position.SPACE);
	steps.add(beat);
	beat = new Beats(2676, Position.A);
	steps.add(beat);
	beat = new Beats(2684, Position.SPACE);
	steps.add(beat);
	beat = new Beats(2697, Position.S);
	steps.add(beat);
	beat = new Beats(2726, Position.K);
	steps.add(beat);
	beat = new Beats(2745, Position.S);
	steps.add(beat);
	beat = new Beats(2756, Position.SPACE);
	steps.add(beat);
	beat = new Beats(2768, Position.S);
	steps.add(beat);
	beat = new Beats(2779, Position.SPACE);
	steps.add(beat);
	beat = new Beats(2790, Position.S);
	steps.add(beat);
	beat = new Beats(2801, Position.SPACE);
	steps.add(beat);
	beat = new Beats(2825, Position.A);
	steps.add(beat);
	beat = new Beats(2843, Position.K);
	steps.add(beat);
	beat = new Beats(2856, Position.S);
	steps.add(beat);
	beat = new Beats(2866, Position.L);
	steps.add(beat);
	beat = new Beats(2877, Position.S);
	steps.add(beat);
	beat = new Beats(2890, Position.K);
	steps.add(beat);
	beat = new Beats(2930, Position.K);
	steps.add(beat);
	beat = new Beats(2951, Position.K);
	steps.add(beat);
	beat = new Beats(2970, Position.L);
	steps.add(beat);
	beat = new Beats(2993, Position.K);
	steps.add(beat);
	beat = new Beats(3014, Position.L);
	steps.add(beat);
	beat = new Beats(3047, Position.S);
	steps.add(beat);
	beat = new Beats(3056, Position.K);
	steps.add(beat);
	beat = new Beats(3067, Position.A);
	steps.add(beat);
	beat = new Beats(3078, Position.L);
	steps.add(beat);
	beat = new Beats(3090, Position.K);
	steps.add(beat);
	beat = new Beats(3102, Position.SPACE);
	steps.add(beat);
	beat = new Beats(3113, Position.S);
	steps.add(beat);
	beat = new Beats(3125, Position.SPACE);
	steps.add(beat);
	beat = new Beats(3134, Position.S);
	steps.add(beat);
	beat = new Beats(3163, Position.SPACE);
	steps.add(beat);
	beat = new Beats(3175, Position.A);
	steps.add(beat);
	beat = new Beats(3187, Position.SPACE);
	steps.add(beat);
	beat = new Beats(3198, Position.S);
	steps.add(beat);
	beat = new Beats(3211, Position.SPACE);
	steps.add(beat);
	beat = new Beats(3232, Position.A);
	steps.add(beat);
	beat = new Beats(3251, Position.A);
	steps.add(beat);
	beat = new Beats(3296, Position.K);
	steps.add(beat);
	beat = new Beats(3316, Position.S);
	steps.add(beat);
	beat = new Beats(3338, Position.SPACE);
	steps.add(beat);
	beat = new Beats(3379, Position.L);
	steps.add(beat);
	beat = new Beats(3399, Position.K);
	steps.add(beat);
	beat = new Beats(3410, Position.S);
	steps.add(beat);
	beat = new Beats(3420, Position.L);
	steps.add(beat);
	beat = new Beats(3432, Position.K);
	steps.add(beat);
	beat = new Beats(3454, Position.L);
	steps.add(beat);
	beat = new Beats(3475, Position.L);
	steps.add(beat);
	beat = new Beats(3498, Position.K);
	steps.add(beat);
	beat = new Beats(3507, Position.L);
	steps.add(beat);
	beat = new Beats(3518, Position.S);
	steps.add(beat);
	beat = new Beats(3528, Position.SPACE);
	steps.add(beat);
	beat = new Beats(3551, Position.A);
	steps.add(beat);
	beat = new Beats(3558, Position.SPACE);
	steps.add(beat);
	beat = new Beats(3572, Position.S);
	steps.add(beat);
	beat = new Beats(3592, Position.SPACE);
	steps.add(beat);
	beat = new Beats(3638, Position.A);
	steps.add(beat);
	beat = new Beats(3656, Position.K);
	steps.add(beat);
	beat = new Beats(3678, Position.S);
	steps.add(beat);
	beat = new Beats(3720, Position.SPACE);
	steps.add(beat);
	beat = new Beats(3741, Position.SPACE);
	steps.add(beat);
	beat = new Beats(3761, Position.SPACE);
	steps.add(beat);
	beat = new Beats(3784, Position.A);
	steps.add(beat);
	beat = new Beats(3802, Position.K);
	steps.add(beat);
	beat = new Beats(3825, Position.S);
	steps.add(beat);
	beat = new Beats(3848, Position.L);
	steps.add(beat);
	beat = new Beats(3870, Position.K);
	steps.add(beat);
	beat = new Beats(3889, Position.A);
	steps.add(beat);
	beat = new Beats(3911, Position.SPACE);
	steps.add(beat);
	beat = new Beats(3922, Position.SPACE);
	steps.add(beat);
	beat = new Beats(3935, Position.SPACE);
	steps.add(beat);
	beat = new Beats(3956, Position.S);
	steps.add(beat);
	beat = new Beats(3979, Position.K);
	steps.add(beat);
	beat = new Beats(3992, Position.L);
	steps.add(beat);
	beat = new Beats(4012, Position.K);
	steps.add(beat);
	beat = new Beats(4024, Position.K);
	steps.add(beat);
	beat = new Beats(4044, Position.K);
	steps.add(beat);
	beat = new Beats(4065, Position.K);
	steps.add(beat);
	beat = new Beats(4084, Position.L);
	steps.add(beat);
	beat = new Beats(4146, Position.A);
	steps.add(beat);
	beat = new Beats(4159, Position.K);
	steps.add(beat);
	beat = new Beats(4197, Position.L);
	steps.add(beat);
	beat = new Beats(4211, Position.S);
	steps.add(beat);
	beat = new Beats(4235, Position.K);
	steps.add(beat);
	beat = new Beats(4246, Position.SPACE);
	steps.add(beat);
	beat = new Beats(4257, Position.S);
	steps.add(beat);
	beat = new Beats(4276, Position.K);
	steps.add(beat);
	beat = new Beats(4297, Position.A);
	steps.add(beat);
	beat = new Beats(4320, Position.L);
	steps.add(beat);
	beat = new Beats(4342, Position.S);
	steps.add(beat);
	beat = new Beats(4384, Position.K);
	steps.add(beat);
	beat = new Beats(4403, Position.L);
	steps.add(beat);
	beat = new Beats(4428, Position.S);
	steps.add(beat);
	beat = new Beats(4470, Position.K);
	steps.add(beat);
	beat = new Beats(4494, Position.L);
	steps.add(beat);
	beat = new Beats(4513, Position.K);
	steps.add(beat);
	beat = new Beats(4535, Position.SPACE);
	steps.add(beat);
	beat = new Beats(4556, Position.A);
	steps.add(beat);
	beat = new Beats(4591, Position.A);
	steps.add(beat);
	beat = new Beats(4603, Position.A);
	steps.add(beat);
	beat = new Beats(4613, Position.A);
	steps.add(beat);
	beat = new Beats(4624, Position.S);
	steps.add(beat);
	beat = new Beats(4635, Position.S);
	steps.add(beat);
	beat = new Beats(4644, Position.S);
	steps.add(beat);
	beat = new Beats(4669, Position.SPACE);
	steps.add(beat);
	beat = new Beats(4686, Position.K);
	steps.add(beat);
	beat = new Beats(4727, Position.L);
	steps.add(beat);
	beat = new Beats(4751, Position.K);
	steps.add(beat);
	beat = new Beats(4771, Position.SPACE);
	steps.add(beat);
	beat = new Beats(4833, Position.K);
	steps.add(beat);
	beat = new Beats(4844, Position.SPACE);
	steps.add(beat);
	beat = new Beats(4893, Position.K);
	steps.add(beat);
	beat = new Beats(4903, Position.SPACE);
	steps.add(beat);
	beat = new Beats(4914, Position.K);
	steps.add(beat);
	beat = new Beats(4925, Position.K);
	steps.add(beat);
	beat = new Beats(4935, Position.SPACE);
	steps.add(beat);
	beat = new Beats(4961, Position.SPACE);
	steps.add(beat);
	beat = new Beats(4980, Position.L);
	steps.add(beat);
	beat = new Beats(5003, Position.S);
	steps.add(beat);
	beat = new Beats(5026, Position.L);
	steps.add(beat);
	beat = new Beats(5069, Position.K);
	steps.add(beat);
	beat = new Beats(5091, Position.A);
	steps.add(beat);
	beat = new Beats(5114, Position.S);
	steps.add(beat);
	beat = new Beats(5160, Position.L);
	steps.add(beat);
	beat = new Beats(5179, Position.S);
	steps.add(beat);
	beat = new Beats(5196, Position.K);
	steps.add(beat);
	beat = new Beats(5260, Position.A);
	steps.add(beat);
	beat = new Beats(5273, Position.L);
	steps.add(beat);
	beat = new Beats(5286, Position.S);
	steps.add(beat);
	beat = new Beats(5296, Position.K);
	steps.add(beat);
	beat = new Beats(5307, Position.SPACE);
	steps.add(beat);
	beat = new Beats(5316, Position.A);
	steps.add(beat);
	beat = new Beats(5326, Position.K);
	steps.add(beat);
	beat = new Beats(5359, Position.S);
	steps.add(beat);
	beat = new Beats(5370, Position.K);
	steps.add(beat);
	beat = new Beats(5402, Position.S);
	steps.add(beat);
	beat = new Beats(5413, Position.SPACE);
	steps.add(beat);
	beat = new Beats(5491, Position.L);
	steps.add(beat);
	beat = new Beats(5500, Position.A);
	steps.add(beat);
	beat = new Beats(5508, Position.K);
	steps.add(beat);
	beat = new Beats(5518, Position.S);
	steps.add(beat);
	beat = new Beats(5526, Position.SPACE);
	steps.add(beat);
	beat = new Beats(5536, Position.S);
	steps.add(beat);
	beat = new Beats(5547, Position.S);
	steps.add(beat);
	beat = new Beats(5558, Position.S);
	steps.add(beat);
	beat = new Beats(5581, Position.A);
	steps.add(beat);
	beat = new Beats(5612, Position.S);
	steps.add(beat);
	beat = new Beats(5634, Position.S);
	steps.add(beat);
	beat = new Beats(5647, Position.S);
	steps.add(beat);
	beat = new Beats(5669, Position.SPACE);
	steps.add(beat);
	beat = new Beats(5690, Position.S);
	steps.add(beat);
	beat = new Beats(5710, Position.SPACE);
	steps.add(beat);
	beat = new Beats(5722, Position.SPACE);
	steps.add(beat);
	beat = new Beats(5734, Position.SPACE);
	steps.add(beat);
	beat = new Beats(5754, Position.S);
	steps.add(beat);
	beat = new Beats(5789, Position.L);
	steps.add(beat);
	beat = new Beats(5810, Position.L);
	steps.add(beat);
	beat = new Beats(5822, Position.L);
	steps.add(beat);
	beat = new Beats(5843, Position.K);
	steps.add(beat);
	beat = new Beats(5853, Position.SPACE);
	steps.add(beat);
	beat = new Beats(5884, Position.S);
	steps.add(beat);
	beat = new Beats(5899, Position.S);
	steps.add(beat);
	beat = new Beats(5926, Position.SPACE);
	steps.add(beat);
	beat = new Beats(5958, Position.A);
	steps.add(beat);
	beat = new Beats(5980, Position.K);
	steps.add(beat);
	beat = new Beats(5989, Position.S);
	steps.add(beat);
	beat = new Beats(6009, Position.SPACE);
	steps.add(beat);
	beat = new Beats(6030, Position.A);
	steps.add(beat);
  }
  
  @Override
  protected void setVariables() {
	song = "/rules/BeatIt/Music/Hatsune Miku - World Is Mine.wav";
	pads = "/rules/BeatIt/BeatItImages/Pad.png";
	beats = "/rules/BeatIt/BeatItImages/Blue-Star-Beat.png";
	background = "/rules/BeatIt/BeatItImages/Hatsune-Miku-Background.jpg";
	pregame = "/rules/BeatIt/BeatItImages/Pregame-Screen.jpg";
	duration = 6200;
  }
  
//  public static void main(String[] args) {
//	Song song = new Hatsune_Miku_World_Is_Mine();
//	song.print();
//  }

}
